spring:
  application:
    name: otc-web
  profiles:
    active: dev
  session:
    store-type: none
  resources:
    static-locations: classpath:/static/
    chain:
      cache: true #开启 chain cache
      gzipped: true
      # 使用 MD5 作为版本号
      strategy:
        content:
          enabled: true
          paths: /**
    # http 缓存过期时间 todo 生产可配置提高性能
#    cache-period: 60

  freemarker:
    request-context-attribute: request
    allow-request-override: false
    allow-session-override: false
    enabled: true
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always


server:
  undertow:
    #设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 50
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    max-http-post-size: 1024
